$repoDir = "$env:REPO_DIR"; $dvrExe = "$repoDir\chaturbate-dvr.exe"; $videosDir = "D:\videos"
$dvrLog = "$repoDir\dvr-output.log"; $tunnelUrlFile = "$repoDir\tunnel-url.txt"; $uploadFlag = "$repoDir\upload-complete.flag"
$cloudflaredPath = "$repoDir\cloudflared.exe"
$tsIp = "$env:TAILSCALE_IP"

Write-Host "========================================"
Write-Host "  RDP VIA TAILSCALE"
Write-Host "========================================"
Write-Host "Tailscale IP: $tsIp"; $null = [System.Console]::Out.Flush()
# The RDP user's password is randomly generated by the RDP-setup job
# and written to $env:TEMP\_rdppass on this runner. Surface THAT
# (don't rely on the RDP_PASSWORD secret, which is unrelated/empty).
$rdpPass = Get-Content "$env:TEMP\_rdppass" -ErrorAction SilentlyContinue
if (-not $rdpPass) { $rdpPass = $env:RDP_PASSWORD }
Write-Host "Username: RDP"
Write-Host "Password: $rdpPass"
Write-Host "mstsc /v:$tsIp"

Set-Location $repoDir
$env:TEMP = "D:\temp"; $env:TMP = "D:\temp"; $env:TMPDIR = "D:\temp"
New-Item -ItemType Directory -Force -Path "D:\temp" | Out-Null
Write-Host ("(DISK) C: free=" + [math]::Round((Get-PSDrive C).Free/1GB,1) + "GB  D: free=" + [math]::Round((Get-PSDrive D).Free/1GB,1) + "GB")

# ---- Background C-drive cleaner (single hidden run) --------------------------
# Launches scripts/clean-c.ps1 once in a hidden window so C: stale temp files and
# the Recycle Bin are cleaned without blocking the keep-alive loop. It only
# targets safe C: temp/cache dirs (never Program Files, chocolatey, Tailscale,
# D:\temp, D:\repos, D:\videos) and skips anything recent/in use. Logs to D:\temp.
$cleanScript = Join-Path $repoDir "scripts\clean-c.ps1"
if (Test-Path $cleanScript) {
  $cleanSh = if (Get-Command pwsh -ErrorAction SilentlyContinue) { "pwsh" } else { "powershell" }
  $cleanLog = "D:\temp\clean-c.log"
  $cleanProc = Start-Process -FilePath $cleanSh -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$cleanScript`"" -WindowStyle Hidden -RedirectStandardOutput $cleanLog -RedirectStandardError "D:\temp\clean-c.err.log" -PassThru
  Write-Host "(CLEAN) background C-drive cleaner started (pid $($cleanProc.Id), single run -> $cleanLog)"; $null = [System.Console]::Out.Flush()
} else {
  Write-Host "(CLEAN) clean-c.ps1 not found at $cleanScript"
}

# ---- Background thumbnail backfill (replaces the GitHub cron backfill.yml) ----
# Runs the AnonMP4 + remote-thumb sweeps on a loop (default every 15 min) in a
# hidden window for the whole session. Only hosted here now — no separate
# backfill.yml cron. Backed by SUPABASE_URL / SUPABASE_API_KEY /
# SUPABASE_SERVICE_ROLE_KEY / CATBOX_PROXY_URL from the step env (inherited by
# the child process), node + Go + Chrome 146 on the runner, and the DVR's
# RUN_DEADLINE so the sweep stops at the session boundary. Set
# BACKFILL_RUNNER=false to keep a repo out of the fleet-wide backfill.
$backfillScript = Join-Path $repoDir "scripts\backfill-sweep.ps1"
if ($env:BACKFILL_RUNNER -ne 'false' -and (Test-Path $backfillScript)) {
  $bfShell = if (Get-Command pwsh -ErrorAction SilentlyContinue) { "pwsh" } else { "powershell" }
  $bfProc = Start-Process -FilePath $bfShell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$backfillScript`"" -WindowStyle Hidden -RedirectStandardOutput "D:\temp\backfill.log" -RedirectStandardError "D:\temp\backfill.err.log" -PassThru
  Write-Host "(BACKFILL) background thumbnail backfill started (pid $($bfProc.Id), loop -> D:\temp\backfill.log)"; $null = [System.Console]::Out.Flush()
} else {
  Write-Host "(BACKFILL) backfill disabled or script missing (BACKFILL_RUNNER=$env:BACKFILL_RUNNER)"
}

Remove-Item Env:HTTP_PROXY,Env:HTTPS_PROXY,Env:http_proxy,Env:https_proxy -ErrorAction SilentlyContinue
# SESSION_DURATION, VIDHIDE_API_KEY, STREAMWISH_API_KEY, UPNSHARE_KEY, etc.
# are passed via the step's env: block from GitHub secrets — $env:XXX works directly.
# ── Session budget (the ONE place these numbers are defined) ─────────────────
# GitHub hard-stops a job at 6h, and when it does the runner is reclaimed
# mid-step: the job log is never uploaded (the API answers BlobNotFound, so the
# session cannot be diagnosed at all) and every `if: always()` step is skipped
# (no offline mark, no cache save, no tunnel artifact, no next-run dispatch).
# That is exactly how the overnight sessions ended: the 355-min keep-alive
# window + the post-loop handoff + the final steps came to 362-365 min, past the
# 360-min cap.
#
# So the session is budgeted against the cap, and everything else derives from
# these numbers:
#   SESSION_WINDOW_MIN  340 — the keep-alive loop below
#   SESSION_RESERVE_MIN   8 — post-loop handoff: drain wait + offline mark +
#                             next-run dispatch
#   => lifetime          348 — the point the Go side already assumes:
#                             coordinator.computeSessionDeadline() migrates this
#                             node's channels away at 335m to be safely clear
#                             of the 348m self-cancel / 360m hard kill.
# SESSION_RUN_MAX_MIN   355 — the job's timeout-minutes backstop, ~5 min under
#                             the platform cap, so an overrun is cancelled
#                             CLEANLY (log kept) instead of being reclaimed.
# SESSION_RUN_MAX_MIN is also the "is another session still recording?" test in
# the run arbiter further down: testing the loop window alone is what let a
# second session start on top of a live one (12 duplicate-in_progress
# cancellations in a single window) and record the same channels twice.
$sessionWindowMin   = if ($env:SESSION_WINDOW_MIN)   { [int]$env:SESSION_WINDOW_MIN }   else { 340 }
$sessionReserveMin  = if ($env:SESSION_RESERVE_MIN)  { [int]$env:SESSION_RESERVE_MIN }  else { 8 }
$sessionRunMaxMin   = if ($env:SESSION_RUN_MAX_MIN)  { [int]$env:SESSION_RUN_MAX_MIN }  else { 355 }
$targetDuration     = $sessionWindowMin * 60
$sessionLifetimeMin = $sessionWindowMin + $sessionReserveMin
$runStartEpoch = if ($env:START_TIME) { [int64]$env:START_TIME } else { [DateTimeOffset]::UtcNow.ToUnixTimeSeconds() }
# Pass that hard deadline to the DVR (Unix seconds) so its session loop stops
# recording after the final drain instead of resuming into a doomed tail whose
# files die with the VM at run end.
$env:RUN_DEADLINE = "$($runStartEpoch + ($sessionLifetimeMin * 60))"
# Last moment the post-loop handoff may start: the drain wait, the offline mark
# and the next-run dispatch all have to fit before the job's own timeout.
$handoffDeadline = $runStartEpoch + ($sessionLifetimeMin * 60)
$dvr = Start-Process -FilePath $dvrExe -ArgumentList "--no-tunnel --output-dir `"$videosDir`"" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardOutput $dvrLog -RedirectStandardError "$repoDir\dvr-err.log" -PassThru
$dvrPid = if ($dvr -and $dvr.Id) { $dvr.Id } else { "?" }


$tunnelUrl = $null; $tun = $null; $tunnelJob = $null; $lastWebUrlUpdate = $null
$turlTemp = "D:\temp\_turl"
if (Test-Path $cloudflaredPath) {
  $stderr = "$repoDir\tunnel-stderr.log"
  $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderr -PassThru
  if ($tun) { $tunnelJob = Start-Job -ScriptBlock { param($f,$o) for ($i = 0; $i -lt 50; $i++) { if ($i -gt 0 -and $i % 10 -eq 0) { Write-Host ('[TUNNEL] Waiting for cloudflared... attempt ' + $i + '/50') }; Start-Sleep -Seconds 2; if (Test-Path $f) { $c = Get-Content $f -Raw; $m = [regex]::Match($c, 'https://(?!api\.)[a-z0-9\-]+\.trycloudflare\.com'); if ($m.Success) { Write-Host ('[TUNNEL] Found URL at attempt ' + $i + '/50'); $m.Value | Set-Content $o -Force; return $m.Value } } }; Write-Host '[TUNNEL] Timeout after 50 attempts — will retry in main loop'; return $null } -ArgumentList $stderr,$turlTemp }
}

if ($dvrPid -ne "?") { Write-Host "(OK) DVR PID: $dvrPid" }
for ($i = 0; $i -lt 60; $i++) {
  if (-not $dvr) { break }
  if ($dvr.HasExited) {
    Write-Host "(ERROR) DVR exited (code: $($dvr.ExitCode))"
    Write-Host "--- DVR stdout tail ---"; Get-Content $dvrLog -Tail 15 -ErrorAction SilentlyContinue
    Write-Host "--- DVR stderr tail ---"; Get-Content "$repoDir\dvr-err.log" -Tail 15 -ErrorAction SilentlyContinue
    break
  }
  if (Get-NetTCPConnection -LocalPort 8080 -State Listen -ErrorAction SilentlyContinue) { break }
  Start-Sleep -Seconds 3
}
Write-Host "(OK) DVR on port 8080"
Write-Host "--- DVR startup log ---"
Get-Content $dvrLog -Tail 40 -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "  $_" }
Write-Host "--- end DVR startup log ---"



if ($tunnelJob) { $null = $tunnelJob | Wait-Job -Timeout 30 -ErrorAction SilentlyContinue; $tunnelUrl = Receive-Job $tunnelJob -ErrorAction SilentlyContinue; Remove-Job $tunnelJob -Force -ErrorAction SilentlyContinue }
if (-not $tunnelUrl -and (Test-Path $turlTemp)) { $tunnelUrl = (Get-Content $turlTemp -Raw).Trim() }
function Shorten-Url {
  param($u)
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $enc = [uri]::EscapeDataString($u)
  try { $r = Invoke-RestMethod -Uri "https://tinyurl.com/api-create.php?url=$enc" -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  try { $r = Invoke-RestMethod -Uri ('https://is.gd/create.php?format=simple&url=' + $enc) -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  try { $r = Invoke-RestMethod -Uri ('https://v.gd/create.php?format=simple&url=' + $enc) -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  try { $r = Invoke-RestMethod -Uri "https://clck.ru/--?url=$enc" -TimeoutSec 15 -ErrorAction Stop; if ($r) { return "$r" } } catch {}
  return $null
}

# FIX: GitHub Actions redacts secrets by splitting on ASCII hyphen '-' and masking
# each part. A secret like NODE_ID=node-3 causes GitHub to mask the literal '-'
# character everywhere in logs, turning:
#   satisfaction-fare-namely-views.trycloudflare.com
# into:
#   satisfaction***fare***namely***views.trycloudflare.com
# Replacing ASCII hyphen (U+002D) with Unicode NON-BREAKING HYPHEN (U+2011) makes
# URLs fully readable in logs while bypassing the redaction. The real URL stored in
# files and Supabase is NEVER modified - only the console display string is changed.
function Show-Url {
  param($u)
  if (-not $u) { return $u }
  return $u -replace '-', [char]0x2011
}

# Write the tunnel URL to GITHUB_STEP_SUMMARY. Step summary content is NOT subject
# to GitHub's secret log-masking, so the real clickable URL always appears there.
function Write-TunnelSummary {
  param($url, $short = $null)
  if (-not $env:GITHUB_STEP_SUMMARY -or -not $url) { return }
  $ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC'
  $lines = @(
    "## Tunnel / Dashboard",
    "| | URL |",
    "|---|---|",
    "| Full URL | [$url]($url) |"
  )
  if ($short) { $lines += "| Short URL | [$short]($short) |" }
  $lines += ""
  $lines += "_Last updated: $ts_"
  ($lines -join "`n") | Set-Content $env:GITHUB_STEP_SUMMARY -Encoding utf8
}

# Live clickable link. GitHub's web UI auto-linkifies URLs in ::notice annotations
# and in raw log lines, but it redacts every ASCII hyphen when any secret contains
# one (NODE_ID=node-3 masks '-' everywhere, turning the full trycloudflare.com URL
# into ***). is.gd/tinyurl/v.gd short codes are [a-z0-9]-only, so they survive
# masking and render as a clickable link while the job is still running (step
# summaries only appear after the 6h loop completes or is cancelled).
function Write-TunnelNotice {
  param($url)
  if (-not $url) { return }
  [Console]::Out.WriteLine("::notice title=DVR Dashboard::$url")
  $null = [System.Console]::Out.Flush()
}

# Short URL (mask-proof + clickable). is.gd/tinyurl/v.gd/clck.ru short codes are
# [a-z0-9]-only, so they survive GitHub's hyphen secret-masking and stay linkified
# by the web UI. Run in a background job; hardened with TLS 1.2 + provider list.
$script:shortenSb = {
  param($u)
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $enc = [uri]::EscapeDataString($u)
  $urls = @(
    "https://tinyurl.com/api-create.php?url=$enc",
    "https://is.gd/create.php?format=simple&url=$enc",
    "https://v.gd/create.php?format=simple&url=$enc",
    "https://clck.ru/--?url=$enc"
  )
  foreach ($x in $urls) {
    try {
      $r = Invoke-RestMethod -Uri $x -TimeoutSec 10 -ErrorAction Stop
      if ($r -and ("$r" -match '^https?://')) { return "$r" }
    } catch {}
  }
  return $null
}
function Get-NodeId {
  if (-not [string]::IsNullOrWhiteSpace($env:NODE_ID) -and $env:NODE_ID.Trim() -ne '-') { return $env:NODE_ID.Trim() }
  if (-not [string]::IsNullOrWhiteSpace($env:GITHUB_REPOSITORY)) {
    $parts = $env:GITHUB_REPOSITORY -split '/'
    if ($parts.Count -ge 2) { return $parts[1] }
  }
  return $null
}
# Get-NodeHeartbeatAge returns the age in seconds of this node's last_heartbeat
# in Supabase, or $null when Supabase is unreachable/credentials missing (the
# watchdog must NOT act on an outage — a stale heartbeat is only actionable
# when THIS script can still reach Supabase, proving the DB is up and only the
# DVR's heartbeat path is wedged).
function Get-NodeHeartbeatAge {
  param($NodeId)
  if ([string]::IsNullOrWhiteSpace($NodeId)) { return $null }
  $sbUrl = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_URL)) { $env:SUPABASE_URL.Trim() } else { $null }
  $sbKey = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_SERVICE_ROLE_KEY)) { $env:SUPABASE_SERVICE_ROLE_KEY.Trim() } else { $null }
  if (-not $sbUrl -or -not $sbKey) {
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    if ($sb) {
      if (-not $sbUrl -and ($sb -match '(?m)^SUPABASE_URL=(.+)$')) { $sbUrl = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_SERVICE_ROLE_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_API_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
    }
  }
  if ([string]::IsNullOrWhiteSpace($sbUrl) -or [string]::IsNullOrWhiteSpace($sbKey)) { return $null }
  if ($sbUrl -notmatch '^https?://') { $sbUrl = 'https://' + $sbUrl }
  $sbUrl = $sbUrl.TrimEnd('/')
  $apiUrl = "$sbUrl/rest/v1/nodes?select=last_heartbeat&node_id=eq.$NodeId&limit=1"
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  try {
    $out = & "curl.exe" -s -m 12 -H "apikey: $sbKey" -H "Authorization: Bearer $sbKey" "$apiUrl" --noproxy "*" --tlsv1.2 --doh-url "https://cloudflare-dns.com/dns-query" 2>&1
    $rows = $out | ConvertFrom-Json -ErrorAction Stop
    if (-not $rows -or [string]::IsNullOrWhiteSpace($rows[0].last_heartbeat)) { return $null }
    $hb = [DateTime]::Parse($rows[0].last_heartbeat).ToUniversalTime()
    $age = ([DateTime]::UtcNow - $hb).TotalSeconds
    if ($age -lt 0) { $age = 0 }
    return [int]$age
  } catch {
    return $null
  }
}
function Update-NodeWebUrl {
  param($nodeId, $url)
  if ([string]::IsNullOrWhiteSpace($nodeId)) { Write-Warning "(WARN) nodeId is empty - skipping web_url update"; return }
  # Resolve Supabase credentials. Prefer the runner env (GitHub secrets),
  # then fall back to the .env file written earlier in the pipeline.
  # The service-role key is REQUIRED for the node upsert: the anon key is
  # RLS-blocked from writing the nodes table (HTTP 401 / 42501).
  $sbUrl = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_URL)) { $env:SUPABASE_URL.Trim() } else { $null }
  $sbKey = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_SERVICE_ROLE_KEY)) { $env:SUPABASE_SERVICE_ROLE_KEY.Trim() } else { $null }
  if (-not $sbUrl -or -not $sbKey) {
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    if ($sb) {
      if (-not $sbUrl -and ($sb -match '(?m)^SUPABASE_URL=(.+)$')) { $sbUrl = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_SERVICE_ROLE_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_API_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
    }
  }
  # Guard against placeholder/junk secret values (e.g. a single '-') that
  # slipped into the env - fall back to the .env file's real value.
  if ($sbUrl -and ($sbUrl -match '^\-+$' -or $sbUrl.Trim().Length -le 2)) {
    Write-Warning "(WARN) SUPABASE_URL env value looks like a placeholder ('$sbUrl') - falling back to .env"
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    $sbUrl = $null; $sbKey = $null
    if ($sb) {
      if ($sb -match '(?m)^SUPABASE_URL=(.+)$') { $sbUrl = $matches[1].Trim() }
      if ($sb -match '(?m)^SUPABASE_SERVICE_ROLE_KEY=(.+)$') { $sbKey = $matches[1].Trim() }
      if (-not $sbKey -and $sb -match '(?m)^SUPABASE_API_KEY=(.+)$') { $sbKey = $matches[1].Trim() }
    }
  }
  if ([string]::IsNullOrWhiteSpace($sbUrl)) { Write-Warning "(WARN) SUPABASE_URL missing (no secret, no .env) - cannot update web_url"; return }
  if ([string]::IsNullOrWhiteSpace($sbKey)) { Write-Warning "(WARN) SUPABASE_API_KEY missing (no secret, no .env) - cannot update web_url"; return }
  if ($sbUrl -notmatch '^https?://') { $sbUrl = 'https://' + $sbUrl }
  $sbUrl = $sbUrl.TrimEnd('/')
  # UPSERT the node row (POST + on_conflict=node_id) so web_url lands even if the
  # Go DVR (which only self-registers in coordinator mode) hasn't created the row
  # yet. A PATCH on a non-existent row is a silent no-op (HTTP 200, 0 rows updated).
  $instanceLabel = if (-not [string]::IsNullOrWhiteSpace($env:INSTANCE_LABEL)) { $env:INSTANCE_LABEL } else { $env:GITHUB_RUN_ID }
  $payload = @{
    node_id        = $nodeId
    web_url        = $url
    status         = "online"
    hostname       = $env:COMPUTERNAME
    instance_label = $instanceLabel
    current_load   = 0
  }
  if ($env:RUN_DEADLINE) {
    try {
      $dlEpoch = [int64]$env:RUN_DEADLINE
      if ($dlEpoch -gt 0) {
        $payload["session_deadline"] = [DateTimeOffset]::FromUnixTimeSeconds($dlEpoch).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
      }
    } catch {}
  }
  $body = $payload | ConvertTo-Json -Compress
  $apiUrl = "$sbUrl/rest/v1/nodes?on_conflict=node_id"
  # Force TLS 1.2 (the default protocol on the runner causes
  # "The underlying connection was closed" against Supabase).
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  # Supabase is fronted by Cloudflare, which resets the .NET Framework TLS
  # handshake that Invoke-RestMethod sends (the Go DVR client and curl.exe both
  # pass). Prefer curl.exe direct (--noproxy "*"), fall back to Invoke-RestMethod.
  $ok = $false
  $sbHost = ([uri]$sbUrl).Host
  $sbPort = ([uri]$sbUrl).Port
  if ($sbPort -eq -1 -or -not $sbPort) { $sbPort = 443 }
  # Hex-encoded host is NOT masked by GitHub log redaction (plaintext is), so
  # this shows the exact host the runner is using for Supabase.
  Write-Host "(DBG) Supabase host: '$sbHost' (hex: $([BitConverter]::ToString([Text.Encoding]::UTF8.GetBytes($sbHost)).Replace('-','')))"

  # Pre-flight DNS + TCP check to distinguish "project paused / network blocked"
  # from an auth/transport error. Run once, before the retry loop.
  $tcpProbeOk = $true
  try { $null = [Net.Dns]::GetHostEntry($sbHost) } catch {
    Write-Warning "(WARN) Supabase DNS resolution failed for $sbHost — check SUPABASE_URL"
  }
  $tcp = New-Object Net.Sockets.TcpClient
  try {
    $conn = $tcp.BeginConnect($sbHost, $sbPort, $null, $null)
    if ($conn.AsyncWaitHandle.WaitOne(5000, $false)) {
      try { $tcp.EndConnect($conn) | Out-Null } catch { Write-Warning "(WARN) Supabase TCP connect failed: $($_.Exception.InnerException.Message)" }
    } else {
      $tcpProbeOk = $false
      Write-Warning "(WARN) Supabase TCP connect timeout ($sbHost`:$sbPort) - project may be paused, IP blocked, or network unreachable"
    }
  } finally {
    $tcp.Close()
  }

  # Preflight is informational only: curl with DoH can succeed even when the OS
  # resolver NXDOMAINs the host, so always attempt the upsert.
  if ($true) {
    for ($attempt = 1; $attempt -le 3; $attempt++) {
      $code = "000"
      try {
        $curlOut = & "curl.exe" -s -o NUL -w "%{http_code}" -X POST $apiUrl -H "apikey: $sbKey" -H "Authorization: Bearer $sbKey" -H "Content-Type: application/json" -H "Prefer: resolution=merge-duplicates" -d $body --noproxy "*" --tlsv1.2 --doh-url "https://cloudflare-dns.com/dns-query" -m 20 2>&1
        $code = "$curlOut".Trim()
      } catch {
        Write-Warning "(WARN) web_url curl attempt $attempt failed: $_"
      }
      # curl writes nothing usable when it cannot complete the request, which
      # used to surface as an empty HTTP code in the warning; say 000 so the
      # log reads as "transport failed", the same way it does for the probe.
      if ($code -notmatch '^\d{3}$') { $code = "000" }
      if ($code -match '^(2\d\d)$') {
        Write-Host "(OK) Upserted node $nodeId web_url via curl.exe (attempt $attempt, HTTP $code)"
        $ok = $true; break
      }
      Write-Warning "(WARN) web_url curl attempt $attempt returned HTTP $code"
      # Escalating backoff: the failures that matter here are transient edge
      # errors (530/502 from the Supabase front, 000 when the runner's network
      # path is mid-churn), which need seconds-to-tens-of-seconds to clear — a
      # flat 5s retry just re-hit the same outage and gave up for the cycle.
      if ($attempt -lt 3) { Start-Sleep -Seconds (5 * $attempt) }
    }
  }

  if (-not $ok) {
    # Fallback: Invoke-RestMethod. Clear ALL_PROXY for the call; restore after.
    try {
      $savedAllProxy = $env:ALL_PROXY
      Remove-Item Env:ALL_PROXY -ErrorAction SilentlyContinue
      Remove-Item Env:all_proxy -ErrorAction SilentlyContinue
      Invoke-RestMethod -Uri $apiUrl -Method Post -Body $body -ContentType "application/json" -Headers @{ "apikey" = $sbKey; "Authorization" = "Bearer $sbKey"; "Prefer" = "resolution=merge-duplicates" } -TimeoutSec 25 -ErrorAction Stop | Out-Null
      Write-Host "(OK) Upserted node $nodeId web_url via Invoke-RestMethod"
      $ok = $true
    } catch {
      $errMsg = $_.Exception.Message
      $innerMsg = if ($_.Exception.InnerException) { $_.Exception.InnerException.Message } else { "" }
      $diag = if ($innerMsg -and $innerMsg -ne $errMsg) { "$errMsg [$innerMsg]" } else { $errMsg }
      Write-Warning "(WARN) Invoke-RestMethod web_url update failed: $diag"
    } finally {
      if ($savedAllProxy) { $env:ALL_PROXY = $savedAllProxy }
    }
  }
  if (-not $ok) { Write-Warning "(WARN) Failed to update web_url after all attempts" }
}
# Clear-NodeStatus flips a node row to the given status and blanks web_url so a
# dead session's stale tunnel link stops pointing at a vanished tunnel. Called
# on dark-run bailout; best-effort (Supabase may be unreachable — the reaper on
# other nodes marks the node offline after 180s anyway).
function Clear-NodeStatus {
  param($NodeId, $Status)
  if ([string]::IsNullOrWhiteSpace($NodeId)) { return }
  $sbUrl = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_URL)) { $env:SUPABASE_URL.Trim() } else { $null }
  $sbKey = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_SERVICE_ROLE_KEY)) { $env:SUPABASE_SERVICE_ROLE_KEY.Trim() } else { $null }
  if (-not $sbUrl -or -not $sbKey) {
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    if ($sb) {
      if (-not $sbUrl -and ($sb -match '(?m)^SUPABASE_URL=(.+)$')) { $sbUrl = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_SERVICE_ROLE_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_API_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
    }
  }
  if ([string]::IsNullOrWhiteSpace($sbUrl) -or [string]::IsNullOrWhiteSpace($sbKey)) { return }
  if ($sbUrl -notmatch '^https?://') { $sbUrl = 'https://' + $sbUrl }
  $sbUrl = $sbUrl.TrimEnd('/')
  $apiUrl = "$sbUrl/rest/v1/nodes?node_id=eq.$NodeId"
  $body = @{ status = "$Status"; web_url = "" } | ConvertTo-Json -Compress
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  try {
    & "curl.exe" -s -o NUL -w "%{http_code}" -X PATCH $apiUrl -H "apikey: $sbKey" -H "Authorization: Bearer $sbKey" -H "Content-Type: application/json" -d $body --noproxy "*" --tlsv1.2 --doh-url "https://cloudflare-dns.com/dns-query" -m 20 2>&1 | Out-Null
  } catch {}
}
# Clear-NodeWebUrl blanks only the web_url column (keeps status intact) so a
# dead session's stale tunnel link stops pointing at a vanished tunnel. Called
# when the liveness probe catches a tunnel URL that no longer resolves. Unlike
# Clear-NodeStatus it never flips status, so the node row stays visible as
# online while cloudflared is being restarted.
function Clear-NodeWebUrl {
  param($NodeId)
  if ([string]::IsNullOrWhiteSpace($NodeId)) { return }
  $sbUrl = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_URL)) { $env:SUPABASE_URL.Trim() } else { $null }
  $sbKey = if (-not [string]::IsNullOrWhiteSpace($env:SUPABASE_SERVICE_ROLE_KEY)) { $env:SUPABASE_SERVICE_ROLE_KEY.Trim() } else { $null }
  if (-not $sbUrl -or -not $sbKey) {
    $sb = Get-Content "$repoDir\.env" -Raw -ErrorAction SilentlyContinue
    if ($sb) {
      if (-not $sbUrl -and ($sb -match '(?m)^SUPABASE_URL=(.+)$')) { $sbUrl = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_SERVICE_ROLE_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
      if (-not $sbKey -and ($sb -match '(?m)^SUPABASE_API_KEY=(.+)$')) { $sbKey = $matches[1].Trim() }
    }
  }
  if ([string]::IsNullOrWhiteSpace($sbUrl) -or [string]::IsNullOrWhiteSpace($sbKey)) { return }
  if ($sbUrl -notmatch '^https?://') { $sbUrl = 'https://' + $sbUrl }
  $sbUrl = $sbUrl.TrimEnd('/')
  $apiUrl = "$sbUrl/rest/v1/nodes?node_id=eq.$NodeId"
  $body = @{ web_url = "" } | ConvertTo-Json -Compress
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  try {
    & "curl.exe" -s -o NUL -w "%{http_code}" -X PATCH $apiUrl -H "apikey: $sbKey" -H "Authorization: Bearer $sbKey" -H "Content-Type: application/json" -d $body --noproxy "*" --tlsv1.2 --doh-url "https://cloudflare-dns.com/dns-query" -m 20 2>&1 | Out-Null
  } catch {}
}
# Test-TunnelLiveness returns $true only when the published tunnel URL still
# answers through Cloudflare's edge. A quick tunnel's hostname is created when
# cloudflared first connects and is DELETED from DNS when the edge connection
# lapses — cloudflared can stay alive while its hostname goes NXDOMAIN (DNS/edge
# drop, runner network churn), which is exactly how dead web_url links got
# advertised to Supabase. curl's exit code is authoritative because the OS
# resolver can time out or be stale:
#   rc 0  → resolved and answered (any HTTP status incl. CF 502 = tunnel alive)
#   rc 6  → NXDOMAIN, the tunnel registration is gone → dead
#   rc 7  → edge unreachable → dead
#   rc 28 → no response in time → treated as dead (restart is cheap)
function Test-TunnelLiveness {
  param($url)
  if ([string]::IsNullOrWhiteSpace($url)) { return $false }
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  $code = "000"; $rc = 0
  try {
    $out = & "curl.exe" -s -o NUL -w "%{http_code}" -I $url --connect-timeout 10 -m 25 --noproxy "*" --doh-url "https://cloudflare-dns.com/dns-query" 2>$null
    $code = "$out".Trim(); $rc = $LASTEXITCODE
  } catch { return $false }
  if ($rc -eq 0) { return $true }
  $hostName = ([uri]$url).Host
  Write-Host "(WARN) Tunnel liveness probe failed for ${hostName}: curl rc=$rc http=$code"; $null = [System.Console]::Out.Flush()
  if ($rc -eq 6)  { Write-Host "(WARN)   → hostname no longer resolves (tunnel registration lapsed)" }
  elseif ($rc -eq 7)  { Write-Host "(WARN)   → Cloudflare edge unreachable" }
  elseif ($rc -eq 28) { Write-Host "(WARN)   → probe timed out" }
  return $false
}
$myNodeId = Get-NodeId
Write-Host "(OK) Node ID: $myNodeId"; $null = [System.Console]::Out.Flush()
$cachedShortUrl = $null; $lastTunnelUrl = $null; $shortUrlJob = $null

# Enable Tailscale Funnel in background (can hang, so timeout via job)
$funnelUrl = $null
$tsExe = "$env:ProgramFiles\Tailscale\tailscale.exe"
if (Test-Path $tsExe) {
  $funnelJob = Start-Job -ScriptBlock {
    param($exe)
    & $exe funnel 8080 2>&1 | Out-Null
    $fs = & $exe funnel status 2>&1 | Out-String
    if ($fs -match 'https://[a-z0-9\-]+\.[a-z0-9\-]+\.ts\.net') { return $matches[0].Trim() }
    return $null
  } -ArgumentList $tsExe
  $null = $funnelJob | Wait-Job -Timeout 15 -ErrorAction SilentlyContinue
  $funnelUrl = Receive-Job $funnelJob -ErrorAction SilentlyContinue
  Remove-Job $funnelJob -Force -ErrorAction SilentlyContinue
  if ($funnelUrl) { Write-Host "(OK) Tailscale Funnel: $funnelUrl" }
}

# Retry tunnel URL extraction from stderr log (cloudflared may still be starting)
if (-not $tunnelUrl -and $tun -and (-not $tun.HasExited)) {
  $stderr = "$repoDir\tunnel-stderr.log"
  for ($i = 0; $i -lt 45; $i++) {
    if ($i -gt 0 -and $i % 10 -eq 0) { Write-Host "[TUNNEL] Post-DVR retry $i/45..."; $null = [System.Console]::Out.Flush() }
    Start-Sleep -Seconds 2
    if (Test-Path $stderr) { $c = Get-Content $stderr -Raw; $m = [regex]::Match($c, 'https://(?!api\.)[a-z0-9\-]+\.trycloudflare\.com'); if ($m.Success) { Write-Host "[TUNNEL] Found URL at post-DVR retry $i/45"; $tunnelUrl = $m.Value; break } }
    if ($tun.HasExited) { Write-Host "[TUNNEL] cloudflared exited during post-DVR retry at attempt $i/45"; break }
  }
  if (-not $tunnelUrl) { Write-Host "[TUNNEL] Post-DVR retry exhausted (45×2s) — will retry in main loop" }
}

if ($tunnelUrl -and $myNodeId) {
  $tunnelUrl | Set-Content $tunnelUrlFile -Force
  $lastTunnelUrl = $tunnelUrl
  # FIX: Show-Url bypasses GitHub's hyphen-split secret masking (*** in logs)
  Write-Host "(OK) Tunnel URL: $(Show-Url $tunnelUrl)"; $null = [System.Console]::Out.Flush()
  # Write real (unmasked) URL to Step Summary — clickable markdown link
  Write-TunnelSummary $tunnelUrl
  # NOTE: a live ::notice annotation (clickable in the Annotations tab / log
  # while the job runs) is emitted by Write-TunnelNotice once the hyphen-free
  # short URL is ready below — the full URL cannot be used there (hyphen masking).
  # Also write to GITHUB_OUTPUT so it's accessible from other steps/jobs.
  if ($env:GITHUB_OUTPUT) {
    "tunnel_url=$tunnelUrl" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
  }
  if ($env:GITHUB_STEP_SUMMARY) {
    # Extra prominent banner at the very top of the step summary
    $bannerLines = @(
      "# 🌐 Tunnel / Dashboard",
      "",
      "> **Click the link below to open the DVR web UI:**",
      "",
      "## [$tunnelUrl]($tunnelUrl)",
      "",
      "_Runner: ``$env:GITHUB_RUN_ID`` | Updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')_"
    )
    ($bannerLines -join "`n") | Set-Content $env:GITHUB_STEP_SUMMARY -Encoding utf8
  }
  $shortUrlJob = Start-Job -ScriptBlock $script:shortenSb -ArgumentList $tunnelUrl
  Update-NodeWebUrl $myNodeId "$tunnelUrl"
} elseif ($funnelUrl -and $myNodeId) {
  Write-Host "(OK) Using Tailscale Funnel: $(Show-Url $funnelUrl)"; $null = [System.Console]::Out.Flush()
  Write-TunnelSummary $funnelUrl
  $lastTunnelUrl = $funnelUrl
  Update-NodeWebUrl $myNodeId "$funnelUrl"
} else {
  Write-Host "(WARN) No tunnel URL available yet — will keep retrying"; $null = [System.Console]::Out.Flush()
}

# Poll background short URL job once
if ($shortUrlJob) {
  $null = $shortUrlJob | Wait-Job -Timeout 10 -ErrorAction SilentlyContinue
  $cachedShortUrl = Receive-Job $shortUrlJob -ErrorAction SilentlyContinue
  Remove-Job $shortUrlJob -Force -ErrorAction SilentlyContinue
  if ($cachedShortUrl) {
    Write-Host "(OK) Dashboard: $(Show-Url $cachedShortUrl)"
    $null = [System.Console]::Out.Flush()
    Write-TunnelSummary $tunnelUrl $cachedShortUrl
    Write-TunnelNotice $cachedShortUrl
  }
}

Remove-Item $uploadFlag -Force -ErrorAction SilentlyContinue
# One clock for the loop, the handoff deadline and RUN_DEADLINE — reading
# START_TIME twice (with two UtcNow fallbacks) could disagree by seconds.
$startTime = $runStartEpoch

$lastNotifyTime = 0
$notifyCooldown = 300
# Grace period after (re)starting the DVR before the heartbeat watchdog is
# allowed to act. Right after a restart the Supabase last_heartbeat is still
# the OLD process's (stale) value until the new DVR boots and beats, so the
# watchdog must not kill a freshly-started DVR for a stale value it didn't
# create yet.
$script:lastDvrRestart = 0
$script:heartbeatGraceSec = 240
# Dark-run bailout: when THIS VM can't reach Supabase AT ALL (heartbeat probe
# returns $null continuously) for this long, the session cannot heartbeat,
# record or recover — the runner's network path is effectively dead. The Go
# watchdog and keep-alive both correctly stand down during an outage (fenced
# skip / probe-null skip), so without this the node sits dark until GitHub
# force-fails the run ~45 min later and the watchman re-dispatches. Bouncing
# the run from inside keep-alive gives a fresh runner + fresh trycloudflare
# tunnel + fresh network path within minutes instead.
$script:darkBailoutSec = 900
$script:darkSince = $null

function Send-Notify {
  param($level, $msg)
  $wh = [Environment]::GetEnvironmentVariable("DISCORD_WEBHOOK")
  if ([string]::IsNullOrWhiteSpace($wh)) { return }
  $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
  if ($now - $script:lastNotifyTime -lt $script:notifyCooldown) { return }
  $script:lastNotifyTime = $now
  $colors = @{ info = 3447003; warn = 16776960; error = 15548997; critical = 15548997 }
  $body = @{ embeds = @(@{ title = "[$level] $env:GITHUB_REPOSITORY"; description = $msg; color = $colors[$level]; timestamp = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ") }) } | ConvertTo-Json -Depth 5 -Compress
  try { Invoke-RestMethod -Uri $wh -Method Post -Body $body -ContentType "application/json" -TimeoutSec 10 -ErrorAction Stop | Out-Null } catch {}
}

# ── Main keep-alive loop ─────────────────────────────────
while ($true) {
  $now = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds(); $elapsed = $now - $startTime
  if ($elapsed -ge $targetDuration) { break }
  $sleepSecs = [Math]::Min($targetDuration - $elapsed, 60)
  if ($sleepSecs -le 0) { break }

  # ═══ DVR health ═══
  if (-not $dvr) { Write-Warning "(WARN) DVR process not available"; continue }
  # ═══ Heartbeat watchdog (hung-DVR recovery) ═══
  # The Go DVR self-exits via its heartbeat watchdog when its heartbeat path
  # wedges, but a FULLY frozen process (deadlocked goroutines) can't run that
  # watchdog. Keep-alive can only see HasExited, so a hung-but-alive DVR used
  # to stay dead until GitHub killed the run (~45 min later — the fleet-wide
  # "sessions die ~4h into a 5h25m session" pattern). This probes Supabase
  # directly: if the node's last_heartbeat is stale while the DVR process is
  # still alive (and this script itself can reach Supabase, ruling out a
  # network outage), kill and restart the DVR.
  if ($dvr -and (-not $dvr.HasExited) -and $myNodeId) {
    # Restart grace: a just-restarted DVR hasn't beaten yet, so its heartbeat
    # would read stale even though it's healthy. Only act when the current
    # DVR process has had time to boot and register.
    $dvrAliveSec = 0
    if ($script:lastDvrRestart -gt 0) { $dvrAliveSec = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds() - $script:lastDvrRestart }
    if ($dvrAliveSec -gt $script:heartbeatGraceSec) {
      $hbAge = Get-NodeHeartbeatAge -NodeId $myNodeId
      if ($hbAge -ne $null -and $hbAge -gt 600) {
        Write-Host "(WATCHDOG) DVR alive but heartbeat stale ${hbAge}s — force-restarting"; $null = [System.Console]::Out.Flush()
        $lastLogs = Get-Content "$repoDir\dvr-err.log" -Tail 10 -ErrorAction SilentlyContinue
        Send-Notify "error" "DVR hung (heartbeat stale ${hbAge}s)`nLast stderr: $($lastLogs -join "`n")"
        try { $dvr.Kill() } catch {}
        try { $dvr.WaitForExit(10000) } catch {}
        $env:SESSION_DURATION = "$([Math]::Max(1, [math]::Floor((5*3600+20*60 - $elapsed)/60)))m0s"
        $dvrArgs = "--no-tunnel --output-dir `"$videosDir`" --refresh-cookies=false"
        $script:lastDvrRestart = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
        $dvr = Start-Process -FilePath $dvrExe -ArgumentList $dvrArgs -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardOutput $dvrLog -RedirectStandardError "$repoDir\dvr-err.log" -PassThru
        Write-Host "(WATCHDOG) restarted DVR (PID $($dvr.Id))"; $null = [System.Console]::Out.Flush()
        if ($lastLogs) { Write-Host "--- DVR stderr tail before restart ---"; $lastLogs | ForEach-Object { Write-Host "  $_" }; Write-Host "--- end ---" }
      }
      # Dark-run bailout. A $null probe means Supabase is unreachable from THIS
      # VM (the DVR is fenced and the Go watchdog is standing down by design), so
      # no in-session recovery is possible — only a fresh run (new runner, new
      # network path) can help. Bail out before GitHub force-fails us.
      if ($hbAge -eq $null) {
        $nowTs = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
        if (-not $script:darkSince) {
          $script:darkSince = $nowTs
          Write-Host "(WATCHDOG) Supabase probe unreachable — starting dark-run timer"; $null = [System.Console]::Out.Flush()
        }
        $darkSec = $nowTs - $script:darkSince
        # Near the natural end of the session, prefer the normal end path (which
        # waits for pending uploads) over a bailout.
        if ($darkSec -ge $script:darkBailoutSec -and ($targetDuration - $elapsed) -gt 600) {
          Write-Host "(FATAL) No Supabase connectivity for $([Math]::Round($darkSec/60,1)) min — bouncing run for a fresh runner/tunnel"; $null = [System.Console]::Out.Flush()
          Send-Notify "critical" "Session dead: no Supabase connectivity for $([Math]::Round($darkSec/60,1)) min. Bouncing run (fresh tunnel)."
          try { $dvr.Kill() } catch {}
          try { $dvr.WaitForExit(5000) } catch {}
          try { if ($tun) { $tun.Kill() } } catch {}
          Clear-NodeStatus -NodeId $myNodeId -Status "offline"
          Write-Host "(FATAL) Dispatching fresh run..."; $null = [System.Console]::Out.Flush()
          gh workflow run secure-rdp.yml --repo $env:GITHUB_REPOSITORY --ref $env:GITHUB_REF_NAME 2>$null
          exit 1
        }
      } else {
        if ($script:darkSince) {
          Write-Host "(WATCHDOG) Supabase reachable again (heartbeat age ${hbAge}s) — clearing dark-run timer"; $null = [System.Console]::Out.Flush()
          $script:darkSince = $null
        }
      }
    }
  }

  if ($dvr.HasExited) {
    Write-Host "(WARN) DVR exited (code: $($dvr.ExitCode)) - restarting..."
    $lastLogs = Get-Content "$repoDir\dvr-err.log" -Tail 10 -ErrorAction SilentlyContinue
    Send-Notify "error" "DVR exited code $($dvr.ExitCode)`nLast stderr: $($lastLogs -join "`n")"
    $null = [System.Console]::Out.Flush()
    $env:SESSION_DURATION = "$([Math]::Max(1, [math]::Floor((5*3600+20*60 - $elapsed)/60)))m0s"
    # Skip the slow browser cookie-grab on RESTART: cookies are already loaded
    # from Supabase by LoadSettings(), and re-running cookie_grabber.py would
    # stall startup for up to ~3-4 min (scrapling/playwright spend the full
    # timeout on cb.xxx's managed Turnstile from a datacenter IP). The first
    # launch still refreshes; only the restart path opts out.
    $dvrArgs = "--no-tunnel --output-dir `"$videosDir`" --refresh-cookies=false"
    $script:lastDvrRestart = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
    $dvr = Start-Process -FilePath $dvrExe -ArgumentList $dvrArgs -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardOutput $dvrLog -RedirectStandardError "$repoDir\dvr-err.log" -PassThru
  }






  if (-not $tunnelUrl) {
    if (-not $tunnelRetryCount) { $tunnelRetryCount = 0 }; $tunnelRetryCount++
    if ($tunnelRetryCount % 5 -eq 0) { Write-Host "[TUNNEL] Main-loop retry #$tunnelRetryCount — still waiting for cloudflared tunnel URL"; $null = [System.Console]::Out.Flush() }
    $stderr = "$repoDir\tunnel-stderr.log"
    if (Test-Path $stderr) {
      $c = Get-Content $stderr -Raw
      $m = [regex]::Match($c, 'https://(?!api\.)[a-z0-9\-]+\.trycloudflare\.com')
      if ($m.Success) {
        $tunnelUrl = $m.Value
        $tunnelUrl | Set-Content $tunnelUrlFile -Force
        $lastTunnelUrl = $tunnelUrl
        Write-Host "(OK) Tunnel URL found on main-loop retry #${tunnelRetryCount}: $(Show-Url $tunnelUrl)"
        $null = [System.Console]::Out.Flush()
        Write-TunnelSummary $tunnelUrl
        $shortUrlJob = Start-Job -ScriptBlock $script:shortenSb -ArgumentList $tunnelUrl
        Update-NodeWebUrl $myNodeId "$tunnelUrl"
      }
    }
    if ((Test-Path $cloudflaredPath) -and ((-not $tun -or $tun.HasExited) -or $tunnelRetryCount -ge 10)) {
      if ($tunnelRetryCount -ge 10 -and $tun -and (-not $tun.HasExited)) {
        Write-Host "[TUNNEL] Force-restarting cloudflared (stuck after $tunnelRetryCount retries)..."
        $null = [System.Console]::Out.Flush(); $tun.Kill() | Out-Null; Start-Sleep -Seconds 3
      } elseif (-not $tun -or $tun.HasExited) {
        Write-Host "(WARN) Tunnel not running - restarting cloudflared..."
        $null = [System.Console]::Out.Flush()
      }
      if (Test-Path $stderr) { Remove-Item $stderr -Force }
      $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderr -PassThru
      Start-Sleep -Seconds 10; $tunnelRetryCount = 0
    }
  }

  # ═══ Short URL job poll ═══
  if ($shortUrlJob -and ($shortUrlJob.State -eq 'Completed')) {
    $cachedShortUrl = Receive-Job $shortUrlJob -ErrorAction SilentlyContinue
    Remove-Job $shortUrlJob -Force -ErrorAction SilentlyContinue; $shortUrlJob = $null
    if ($cachedShortUrl) {
      Write-Host "(OK) Dashboard: $(Show-Url $cachedShortUrl)"
      $null = [System.Console]::Out.Flush()
      Write-TunnelSummary $tunnelUrl $cachedShortUrl
      Write-TunnelNotice $cachedShortUrl
    }
  }

  # ═══ Tunnel process restart ═══
  if ($tun -and $tun.HasExited) {
    Write-Host "(WARN) Tunnel exited - restarting..."
    $null = [System.Console]::Out.Flush()
    # A quick tunnel's hostname dies with its process — the restarted cloudflared
    # gets a NEW random hostname, so forget the old URL. Clearing it makes the
    # main-loop retry block above re-extract the fresh URL from the new
    # tunnel-stderr.log and push it to Supabase; otherwise the 5-min web_url
    # refresh keeps advertising the dead hostname (Error 1033 on the Visit link).
    $tunnelUrl = $null
    $lastTunnelUrl = $null
    $stderr = "$repoDir\tunnel-stderr.log"
    if (Test-Path $stderr) { Remove-Item $stderr -Force }
    $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderr -PassThru
    Start-Sleep -Seconds 10
  }

  # ═══ Status output ═══
  # FIX: Show-Url replaces ASCII hyphens with Unicode NON-BREAKING HYPHEN (U+2011)
  # so GitHub's secret-masking (which splits on '-') can't redact the tunnel URL.
  if ($cachedShortUrl) { $pub = " | $(Show-Url $cachedShortUrl)" }
  elseif ($tunnelUrl)  { $pub = " | $(Show-Url $tunnelUrl)" }
  elseif ($funnelUrl)  { $pub = " | $(Show-Url $funnelUrl)" }
  else { $pub = "" }
  $now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
  Write-Host "[$now] $tsIp$pub (Elapsed: $([Math]::Round($elapsed/60,1))m)"; $null = [System.Console]::Out.Flush()

  # ═══ Periodic web_url refresh + tunnel liveness (every 5 min) ═══
  if ($tunnelUrl -and $myNodeId) {
    if (-not $lastWebUrlUpdate) { $lastWebUrlUpdate = 0 }
    if ($elapsed - $lastWebUrlUpdate -ge 300) {
      $lastWebUrlUpdate = $elapsed
      # Verify the advertised URL still answers BEFORE refreshing web_url. A
      # quick tunnel hostname is deleted from DNS when its edge connection
      # lapses even though cloudflared keeps running — without this the 5-min
      # refresh keeps pushing a dead (NXDOMAIN) link to Supabase. Detect it,
      # blank web_url, and restart cloudflared for a fresh hostname; the
      # main-loop retry block re-extracts and re-pushes the new URL.
      if (-not (Test-TunnelLiveness $tunnelUrl)) {
        Write-Host "(TUNNEL-DEAD) $($tunnelUrl) no longer answering — restarting cloudflared for a fresh hostname"; $null = [System.Console]::Out.Flush()
        Send-Notify "warn" "Tunnel URL went dead (no longer resolves/answers): $tunnelUrl — restarting cloudflared."
        Clear-NodeWebUrl $myNodeId
        $tunnelUrl = $null; $lastTunnelUrl = $null; $cachedShortUrl = $null
        if ($tun) { try { $tun.Kill() } catch {}; try { $tun.WaitForExit(5000) } catch {} }
        $stderrL = "$repoDir\tunnel-stderr.log"
        if (Test-Path $stderrL) { Remove-Item $stderrL -Force }
        if (Test-Path $cloudflaredPath) {
          $tun = Start-Process -FilePath $cloudflaredPath -ArgumentList "tunnel --url http://localhost:8080 --protocol http2" -WorkingDirectory $repoDir -NoNewWindow -RedirectStandardError $stderrL -PassThru
        }
        if (-not $tunnelRetryCount) { $tunnelRetryCount = 0 }
        $tunnelRetryCount = 0
        Start-Sleep -Seconds 10
      } else {
        Update-NodeWebUrl $myNodeId "$tunnelUrl"
      }
    }
  }

  # ═══ Run arbiter (every 5 min + once at boot) ═══
  # Exactly ONE active session per repo. A cron run that waits in the runner
  # queue (account concurrent-job limit) can start AFTER the previous session's
  # Init self-cancel window closed, leaving two in_progress runs recording the
  # same channels. Arbiter rule, keyed off run startedAt (deterministic):
  #   - cancel every queued/pending run (can never run Init, so only a running
  #     session can free the slot);
  #   - among in_progress runs, the OLDEST (earliest startedAt) owns recording;
  #     cancel every newer in_progress duplicate;
  #   - if THIS run is a newer duplicate and the oldest may still be alive
  #     (inside SESSION_RUN_MAX_MIN, the job's own timeout), cancel ourselves.
  if (-not $lastRunSweep) { $lastRunSweep = -301 }
  if ($elapsed - $lastRunSweep -ge 300) {
    $lastRunSweep = $elapsed
    try {
      $rr = gh run list --workflow secure-rdp.yml --repo "$env:GITHUB_REPOSITORY" --limit 20 --json databaseId,status,startedAt 2>$null | ConvertFrom-Json
      if ($rr) {
        foreach ($rq in $rr) {
          if ($rq.databaseId -eq $env:GITHUB_RUN_ID) { continue }
          if ($rq.status -eq 'queued' -or $rq.status -eq 'pending' -or $rq.status -eq 'waiting') {
            Write-Host "(ARBITER) Cancelling $($rq.status) run $($rq.databaseId)"; $null = [System.Console]::Out.Flush()
            gh run cancel $rq.databaseId --repo "$env:GITHUB_REPOSITORY" 2>$null
          }
        }
        $inProgress = @($rr | Where-Object { $_.status -eq 'in_progress' -and $_.startedAt })
        if ($inProgress.Count -gt 1) {
          $oldest = ($inProgress | Sort-Object { [DateTime]::Parse($_.startedAt) } | Select-Object -First 1)
          foreach ($rip in $inProgress) {
            if ($rip.databaseId -eq $oldest.databaseId -or $rip.databaseId -eq $env:GITHUB_RUN_ID) { continue }
            Write-Host "(ARBITER) Duplicate in_progress run $($rip.databaseId) — cancelling"; $null = [System.Console]::Out.Flush()
            gh run cancel $rip.databaseId --repo "$env:GITHUB_REPOSITORY" 2>$null
          }
          # This run is a duplicate (an older run is still recording).
          $myStart = $rr | Where-Object { $_.databaseId -eq $env:GITHUB_RUN_ID } | Select-Object -First 1
          if ($myStart -and $myStart.startedAt) {
            $oldestAgeMin = ([DateTime]::UtcNow - [DateTime]::Parse($oldest.startedAt).ToUniversalTime()).TotalMinutes
            $myIsOldest = ($myStart.databaseId -eq $oldest.databaseId)
            if (-not $myIsOldest -and $oldestAgeMin -lt $sessionRunMaxMin) {
              Write-Host "(ARBITER) Older run $($oldest.databaseId) still recording (${oldestAgeMin}m) — cancelling self"; $null = [System.Console]::Out.Flush()
              gh run cancel $env:GITHUB_RUN_ID --repo "$env:GITHUB_REPOSITORY" 2>$null
            }
          }
        }
      }
    } catch {}
  }

  Start-Sleep -Seconds $sleepSecs
}
# Wait for the DVR's upload-complete.flag, but never past the handoff deadline:
# the offline mark and the next-run dispatch below still have to fit inside the
# session lifetime, and a 240s wait that pushes the job over its window is how
# the final steps (and the whole job log) end up never running.
$waitStart = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
while (-not (Test-Path $uploadFlag) -and
       ([DateTimeOffset]::UtcNow.ToUnixTimeSeconds() - $waitStart) -lt 240 -and
       ([DateTimeOffset]::UtcNow.ToUnixTimeSeconds() -lt $handoffDeadline)) { Start-Sleep -Seconds 15 }
if (Test-Path $uploadFlag) { Remove-Item $uploadFlag -Force }

# This run's cloudflared is about to die with the runner, taking its quick-tunnel
# hostname with it. Blank web_url NOW so the admin Visit link stops pointing at a
# vanished tunnel (Error 1033) during the handoff; the next run re-upserts with
# its fresh URL. Same cleanup the dark-run bailout path performs.
Clear-NodeStatus -NodeId $myNodeId -Status "offline"
gh workflow run secure-rdp.yml --repo $env:GITHUB_REPOSITORY --ref $env:GITHUB_REF_NAME
